var group__RCC__Exported__Macros =
[
    [ "AHB1 Peripheral Clock Enable Disable", "group__RCC__AHB1__Peripheral__Clock__Enable__Disable.html", null ],
    [ "AHB2 Peripheral Clock Enable Disable", "group__RCC__AHB2__Peripheral__Clock__Enable__Disable.html", null ],
    [ "AHB3 Peripheral Clock Enable Disable", "group__RCC__AHB3__Clock__Enable__Disable.html", null ],
    [ "APB1 Peripheral Clock Enable Disable", "group__RCC__APB1__Clock__Enable__Disable.html", null ],
    [ "APB2 Peripheral Clock Enable Disable", "group__RCC__APB2__Clock__Enable__Disable.html", null ],
    [ "AHB1 Peripheral Clock Enabled or Disabled Status", "group__RCC__AHB1__Peripheral__Clock__Enable__Disable__Status.html", null ],
    [ "AHB2 Peripheral Clock Enabled or Disabled Status", "group__RCC__AHB2__Clock__Enable__Disable__Status.html", null ],
    [ "AHB3 Peripheral Clock Enabled or Disabled Status", "group__RCC__AHB3__Clock__Enable__Disable__Status.html", null ],
    [ "APB1 Peripheral Clock Enabled or Disabled Status", "group__RCC__APB1__Clock__Enable__Disable__Status.html", null ],
    [ "APB2 Peripheral Clock Enabled or Disabled Status", "group__RCC__APB2__Clock__Enable__Disable__Status.html", null ],
    [ "AHB1 Peripheral Force Release Reset", "group__RCC__AHB1__Force__Release__Reset.html", null ],
    [ "AHB2 Peripheral Force Release Reset", "group__RCC__AHB2__Force__Release__Reset.html", null ],
    [ "AHB3 Peripheral Force Release Reset", "group__RCC__AHB3__Force__Release__Reset.html", null ],
    [ "APB1 Peripheral Force Release Reset", "group__RCC__APB1__Force__Release__Reset.html", null ],
    [ "APB2 Peripheral Force Release Reset", "group__RCC__APB2__Force__Release__Reset.html", null ],
    [ "AHB1 Peripheral Clock Sleep Enable Disable", "group__RCC__AHB1__Clock__Sleep__Enable__Disable.html", null ],
    [ "AHB2 Peripheral Clock Sleep Enable Disable", "group__RCC__AHB2__Clock__Sleep__Enable__Disable.html", null ],
    [ "AHB3 Peripheral Clock Sleep Enable Disable", "group__RCC__AHB3__Clock__Sleep__Enable__Disable.html", null ],
    [ "APB1 Peripheral Clock Sleep Enable Disable", "group__RCC__APB1__Clock__Sleep__Enable__Disable.html", null ],
    [ "APB2 Peripheral Clock Sleep Enable Disable", "group__RCC__APB2__Clock__Sleep__Enable__Disable.html", null ],
    [ "AHB1 Peripheral Clock Sleep Enabled or Disabled Status", "group__RCC__AHB1__Clock__Sleep__Enable__Disable__Status.html", null ],
    [ "AHB2 Peripheral Clock Sleep Enabled or Disabled Status", "group__RCC__AHB2__Clock__Sleep__Enable__Disable__Status.html", null ],
    [ "AHB3 Peripheral Clock Sleep Enabled or Disabled Status", "group__RCC__AHB3__Clock__Sleep__Enable__Disable__Status.html", null ],
    [ "APB1 Peripheral Clock Sleep Enabled or Disabled Status", "group__RCC__APB1__Clock__Sleep__Enable__Disable__Status.html", null ],
    [ "APB2 Peripheral Clock Sleep Enabled or Disabled Status", "group__RCC__APB2__Clock__Sleep__Enable__Disable__Status.html", null ],
    [ "RCC Backup Domain Reset", "group__RCC__Backup__Domain__Reset.html", null ],
    [ "RCC RTC Clock Configuration", "group__RCC__RTC__Clock__Configuration.html", null ],
    [ "Flags Interrupts Management", "group__RCC__Flags__Interrupts__Management.html", null ]
];