var group__SAI__Exported__Constants =
[
    [ "SAI Error Code", "group__SAI__Error__Code.html", null ],
    [ "SAI External synchronisation", "group__SAI__Block__SyncExt.html", null ],
    [ "SAI Supported protocol", "group__SAI__Protocol.html", null ],
    [ "SAI protocol data size", "group__SAI__Protocol__DataSize.html", null ],
    [ "SAI Audio Frequency", "group__SAI__Audio__Frequency.html", null ],
    [ "SAI Block Master Clock OverSampling", "group__SAI__Block__Mck__OverSampling.html", null ],
    [ "SAI PDM Clock Enable", "group__SAI__PDM__ClockEnable.html", null ],
    [ "SAI Block Mode", "group__SAI__Block__Mode.html", null ],
    [ "SAI Block Protocol", "group__SAI__Block__Protocol.html", null ],
    [ "SAI Block Data Size", "group__SAI__Block__Data__Size.html", null ],
    [ "SAI Block MSB LSB transmission", "group__SAI__Block__MSB__LSB__transmission.html", null ],
    [ "SAI Block Clock Strobing", "group__SAI__Block__Clock__Strobing.html", null ],
    [ "SAI Block Synchronization", "group__SAI__Block__Synchronization.html", null ],
    [ "SAI Block Output Drive", "group__SAI__Block__Output__Drive.html", null ],
    [ "SAI Block NoDivider", "group__SAI__Block__NoDivider.html", null ],
    [ "SAI Block FS Definition", "group__SAI__Block__FS__Definition.html", null ],
    [ "SAI Block FS Polarity", "group__SAI__Block__FS__Polarity.html", null ],
    [ "SAI Block FS Offset", "group__SAI__Block__FS__Offset.html", null ],
    [ "SAI Block Slot Size", "group__SAI__Block__Slot__Size.html", null ],
    [ "SAI Block Slot Active", "group__SAI__Block__Slot__Active.html", null ],
    [ "SAI Mono Stereo Mode", "group__SAI__Mono__Stereo__Mode.html", null ],
    [ "SAI TRIState Management", "group__SAI__TRIState__Management.html", null ],
    [ "SAI Block Fifo Threshold", "group__SAI__Block__Fifo__Threshold.html", null ],
    [ "SAI Block Companding Mode", "group__SAI__Block__Companding__Mode.html", null ],
    [ "SAI Block Mute Value", "group__SAI__Block__Mute__Value.html", null ],
    [ "SAI Block Interrupts Definition", "group__SAI__Block__Interrupts__Definition.html", null ],
    [ "SAI Block Flags Definition", "group__SAI__Block__Flags__Definition.html", null ],
    [ "SAI Block Fifo Status Level", "group__SAI__Block__Fifo__Status__Level.html", null ]
];