var group__USART__LL__Exported__Constants =
[
    [ "Clear Flags Defines", "group__USART__LL__EC__CLEAR__FLAG.html", null ],
    [ "Get Flags Defines", "group__USART__LL__EC__GET__FLAG.html", null ],
    [ "IT Defines", "group__USART__LL__EC__IT.html", null ],
    [ "FIFO Threshold", "group__USART__LL__EC__FIFOTHRESHOLD.html", null ],
    [ "Communication Direction", "group__USART__LL__EC__DIRECTION.html", null ],
    [ "Parity Control", "group__USART__LL__EC__PARITY.html", null ],
    [ "Wakeup", "group__USART__LL__EC__WAKEUP.html", null ],
    [ "Datawidth", "group__USART__LL__EC__DATAWIDTH.html", null ],
    [ "Oversampling", "group__USART__LL__EC__OVERSAMPLING.html", null ],
    [ "Clock Signal", "group__USART__LL__EC__CLOCK.html", null ],
    [ "Last Clock Pulse", "group__USART__LL__EC__LASTCLKPULSE.html", null ],
    [ "Clock Phase", "group__USART__LL__EC__PHASE.html", null ],
    [ "Clock Polarity", "group__USART__LL__EC__POLARITY.html", null ],
    [ "Clock Source Prescaler", "group__USART__LL__EC__PRESCALER.html", null ],
    [ "Stop Bits", "group__USART__LL__EC__STOPBITS.html", null ],
    [ "TX RX Pins Swap", "group__USART__LL__EC__TXRX.html", null ],
    [ "RX Pin Active Level Inversion", "group__USART__LL__EC__RXPIN__LEVEL.html", null ],
    [ "TX Pin Active Level Inversion", "group__USART__LL__EC__TXPIN__LEVEL.html", null ],
    [ "Binary Data Inversion", "group__USART__LL__EC__BINARY__LOGIC.html", null ],
    [ "Bit Order", "group__USART__LL__EC__BITORDER.html", null ],
    [ "Autobaud Detection", "group__USART__LL__EC__AUTOBAUD__DETECT__ON.html", null ],
    [ "Address Length Detection", "group__USART__LL__EC__ADDRESS__DETECT.html", null ],
    [ "Hardware Control", "group__USART__LL__EC__HWCONTROL.html", null ],
    [ "Wakeup Activation", "group__USART__LL__EC__WAKEUP__ON.html", null ],
    [ "IrDA Power", "group__USART__LL__EC__IRDA__POWER.html", null ],
    [ "LIN Break Detection Length", "group__USART__LL__EC__LINBREAK__DETECT.html", null ],
    [ "Driver Enable Polarity", "group__USART__LL__EC__DE__POLARITY.html", null ],
    [ "DMA Register Data", "group__USART__LL__EC__DMA__REG__DATA.html", null ]
];