var group__OSPI__Exported__Constants =
[
    [ "OSPI State", "group__OSPI__State.html", null ],
    [ "OSPI Error Code", "group__OSPI__ErrorCode.html", null ],
    [ "OSPI Dual-Quad", "group__OSPI__DualQuad.html", null ],
    [ "OSPI Memory Type", "group__OSPI__MemoryType.html", null ],
    [ "OSPI Free Running Clock", "group__OSPI__FreeRunningClock.html", null ],
    [ "OSPI Clock Mode", "group__OSPI__ClockMode.html", null ],
    [ "OSPI Wrap-Size", "group__OSPI__WrapSize.html", null ],
    [ "OSPI Sample Shifting", "group__OSPI__SampleShifting.html", null ],
    [ "OSPI Delay Hold Quarter Cycle", "group__OSPI__DelayHoldQuarterCycle.html", null ],
    [ "OSPI Operation Type", "group__OSPI__OperationType.html", null ],
    [ "OSPI Flash Id", "group__OSPI__FlashID.html", null ],
    [ "OSPI Instruction Mode", "group__OSPI__InstructionMode.html", null ],
    [ "OSPI Instruction Size", "group__OSPI__InstructionSize.html", null ],
    [ "OSPI Instruction DTR Mode", "group__OSPI__InstructionDtrMode.html", null ],
    [ "OSPI Address Mode", "group__OSPI__AddressMode.html", null ],
    [ "OSPI Address Size", "group__OSPI__AddressSize.html", null ],
    [ "OSPI Address DTR Mode", "group__OSPI__AddressDtrMode.html", null ],
    [ "OSPI Alternate Bytes Mode", "group__OSPI__AlternateBytesMode.html", null ],
    [ "OSPI Alternate Bytes Size", "group__OSPI__AlternateBytesSize.html", null ],
    [ "OSPI Alternate Bytes DTR Mode", "group__OSPI__AlternateBytesDtrMode.html", null ],
    [ "OSPI Data Mode", "group__OSPI__DataMode.html", null ],
    [ "OSPI Data DTR Mode", "group__OSPI__DataDtrMode.html", null ],
    [ "OSPI DQS Mode", "group__OSPI__DQSMode.html", null ],
    [ "OSPI SIOO Mode", "group__OSPI__SIOOMode.html", null ],
    [ "OSPI Hyperbus Write Zero Latency Activation", "group__OSPI__WriteZeroLatency.html", null ],
    [ "OSPI Hyperbus Latency Mode", "group__OSPI__LatencyMode.html", null ],
    [ "OSPI Hyperbus Address Space", "group__OSPI__AddressSpace.html", null ],
    [ "OSPI Match Mode", "group__OSPI__MatchMode.html", null ],
    [ "OSPI Automatic Stop", "group__OSPI__AutomaticStop.html", null ],
    [ "OSPI Timeout Activation", "group__OSPI__TimeOutActivation.html", null ],
    [ "OSPI Flags", "group__OSPI__Flags.html", null ],
    [ "OSPI Interrupts", "group__OSPI__Interrupts.html", null ],
    [ "OSPI Timeout definition", "group__OSPI__Timeout__definition.html", null ],
    [ "OSPI IO Manager IO Port", "group__OSPIM__IOPort.html", null ]
];